sonar.projectKey=Penjadwalan-Perkuliahan-FT-UNRI-New
sonar.projectName=Penjadwalan Perkuliahan FT UNRI New
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.sources=app
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=app/Modules/Penjadwalan/Infrastructure/Scheduling/Legacy/AlgoritmaGenetika.php,app/Infrastructure/Scheduling/Legacy/**,app/Imports/**,app/Jobs/**,app/Console/**,app/Providers/**,app/Support/**,app/Traits/**,app/Http/**
sonar.test.inclusions=tests/**/*Test.php
sonar.php.coverage.reportPaths=docs/metrics-final/coverage-clover.xml
sonar.php.tests.reportPath=docs/metrics-final/junit.xml
sonar.cpd.php.minimumTokens=50
sonar.cpd.php.minimumLines=8
